#   ____            _                   _ _
# |  _ \ ___   ___| | ____      ____ _| | |
# | |_) / _ \ / __| |/ /\ \ /\ / / _` | | |
# |  _ < (_) | (__|   <  \ V  V / (_| | | |
# |_| \_\___/ \___|_|\_\  \_/\_/ \__,_|_|_|
#
# Plugin created by Cbble_

# Settings for the default chat
# This likely sounds confusing, that's because it is.
# Just know global chat refers to Minecraft's chat
# And groups refer to group chat-like messaging this plugin includes
global-chat:
  # Is the global chat enabled?
  enabled: true

  # These formats are used when speaking globally
  formats:
    # Default format, more can be specified
    default:
      prefix:
        display: "%luckperms_prefix%" # Shown in chat
        hover: # Shown when hovered
          - "Boo"
        on-click: "/suicide" # Ran when hovered
      name:
        display: "%player_name%"
        hover:
          - "%player_name%"
          - "Click to msg"
        on-click: "/msg %player_name%"
      prefix-separator:
        display: "&8|"
        hover:
          -
        on-click: "/msg %player_name%"
      name-separator:
        display: "&8»"
        hover:
          -
        on-click: ""

# Experimental group chat system
# Refers to group chat-like messaging this plugin includes
groups:
  # Are groups enabled?
  enabled: true

  # formats, only normal and (WIP) admin (Admin groups do nothing right now)
  formats:
    normal:
      prefix:
        display: "&7[%chat_alias%]" # Shown in chat
        hover: # Shown when hovered
          - "Boo"
        on-click: "/g msg %chat_alias%" # Ran when hovered
      name:
        display: "%player_name%"
        hover:
          - "%player_name%"
          - "Click to msg privately"
        on-click: "/msg %player_name%"
      prefix-separator:
        display: ""
        hover:
          -
        on-click: ""
      name-separator:
        display: "&8»"
        hover:
          -
        on-click: ""