name: Rockwall
version: '${version}'
main: me.cobble.rockwall.rockwall.Rockwall
api-version: 1.19
softdepend: [ PlaceholderAPI ]
authors: [ Cbble_ ]
description: An advanced, elegant and powerful chat system
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.0'
permissions:
  rockwall.color:
    description: Allows players to send colored messages
    default: op
  rockwall.clearchat:
    default: op
    description: Allows players to clear chat
  rockwall.admin:
    default: op
    description: Allows access to admin commands
commands:
  clearchat:
    aliases:
      - chatclear
      - cc
    description: Clears the global chat
  rockwall:
    aliases:
      - rwall
      - rw
    description: Admin command for Rockwall

